### ISSUE TITLE
stop called on unstarted patcher

### ISSUE THREAD

**Issue by igor-raits** [lukesneeringer/fauxquests#2]
``` python
======================================================================
ERROR: test_fauxquests (test_integration.IntegrationTests)
Ensure that a standard request registration and mock out
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/brain/rpmbuild/BUILD/fauxquests-16d1f71547279fc7862c4b6597fab5524f70b082/tests/test_integration.py", line 21, in test_fauxquests
    self.assertEqual(result.content.decode('utf8'), 'blahblah')
  File "/home/brain/rpmbuild/BUILD/fauxquests-16d1f71547279fc7862c4b6597fab5524f70b082/fauxquests/session.py", line 42, in __exit__
    return self.stop()
  File "/home/brain/rpmbuild/BUILD/fauxquests-16d1f71547279fc7862c4b6597fab5524f70b082/fauxquests/session.py", line 105, in stop
    self.patcher.stop()
  File "/usr/lib/python2.7/site-packages/mock/mock.py", line 1513, in stop
    return self.__exit__()
  File "/usr/lib/python2.7/site-packages/mock/mock.py", line 1477, in __exit__
    raise RuntimeError('stop called on unstarted patcher')
RuntimeError: stop called on unstarted patcher

======================================================================
ERROR: test_method_match (test_integration.IntegrationTests)
Ensure that a method-specific registration is honored,
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/brain/rpmbuild/BUILD/fauxquests-16d1f71547279fc7862c4b6597fab5524f70b082/tests/test_integration.py", line 44, in test_method_match
    result = requests.get('http://www.google.com/')
  File "/home/brain/rpmbuild/BUILD/fauxquests-16d1f71547279fc7862c4b6597fab5524f70b082/fauxquests/session.py", line 42, in __exit__
    return self.stop()
  File "/home/brain/rpmbuild/BUILD/fauxquests-16d1f71547279fc7862c4b6597fab5524f70b082/fauxquests/session.py", line 105, in stop
    self.patcher.stop()
  File "/usr/lib/python2.7/site-packages/mock/mock.py", line 1513, in stop
    return self.__exit__()
  File "/usr/lib/python2.7/site-packages/mock/mock.py", line 1477, in __exit__
    raise RuntimeError('stop called on unstarted patcher')
RuntimeError: stop called on unstarted patcher

======================================================================
ERROR: test_unregistered (test_integration.IntegrationTests)
Ensure that an unregistered URL fails in the way we expect,
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/brain/rpmbuild/BUILD/fauxquests-16d1f71547279fc7862c4b6597fab5524f70b082/tests/test_integration.py", line 29, in test_unregistered
    result = requests.get('http://www.google.com/')
  File "/home/brain/rpmbuild/BUILD/fauxquests-16d1f71547279fc7862c4b6597fab5524f70b082/fauxquests/session.py", line 42, in __exit__
    return self.stop()
  File "/home/brain/rpmbuild/BUILD/fauxquests-16d1f71547279fc7862c4b6597fab5524f70b082/fauxquests/session.py", line 105, in stop
    self.patcher.stop()
  File "/usr/lib/python2.7/site-packages/mock/mock.py", line 1513, in stop
    return self.__exit__()
  File "/usr/lib/python2.7/site-packages/mock/mock.py", line 1477, in __exit__
    raise RuntimeError('stop called on unstarted patcher')
RuntimeError: stop called on unstarted patcher
```

**Comment by igor-raits** [comment]
``` python
Traceback (most recent call last):
  File "/home/brain/rpmbuild/BUILD/fauxquests-16d1f71547279fc7862c4b6597fab5524f70b082/tests/test_integration.py", line 20, in test_fauxquests
    result = requests.get('http://www.google.com/')
  File "/usr/lib/python3.5/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.5/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
AttributeError: 'FauxAdapter' object has no attribute 'request'
```

looks like it's because of this.
